const Post = [
    {
        id: 1,
        postImage: "../images/sofa.jpg",
        prodTitle: "Sofa",
        prodPrice: "₹2000",
        prodDetails: "",
        loc: "Delhi",
    },
    {  id: 2,
        postImage: "../images/w.jpg",
        prodTitle: "Wardrobe",
        prodPrice: "₹2500",
        prodDetails: "",
        loc: "Gurgaon",
    },
    {
        id: 3,
        postImage: "../images/speaker.webp",
        prodTitle: "Speaker",
        prodPrice: "₹2000",
        prodDetails: "",
        loc: "Greater Noida",
    },
    {
        id: 4,
        postImage: "../images/bike.jpeg",
        prodTitle: "Bike",
        prodPrice: "₹5000",
        prodDetails: "",
        loc: "Noida",
    },
    {  id: 5,
        postImage: "",
        prodTitle: "Laptop",
        prodPrice: "₹5000",
        prodDetails: "",
        loc: "Ghaziabad",
    },
    {  id: 6,
        postImage: "../images/fridge.jpeg",
        prodTitle: "Refrigerator",
        prodPrice: "₹7000",
        prodDetails: "",
        loc: "Pune",
    },
    {
        id: 7,
        postImage: "../images/wed.jpeg",
        prodTitle: "Wedding dresses",
        prodPrice: "₹7000",
        prodDetails: "",
        loc: "Mumbai",
    }
];

export default Post;